---
title: "About"
author: "Benzon Carlitos Salazar"
date: "2023-12-28"
output: html_document
---

# About

Hi there! I’m an Informatics Analyst at [Emory University](https://www.emory.edu/home/index.html), 
where I collaborate with researchers to drive data-driven insights that support 
groundbreaking research and healthcare innovation.

In my role, I apply cutting-edge technologies and biomedical informatics standards 
to ensure that our informatics systems advance the university’s research objectives. 
I work closely with researchers to translate their needs into effective technical 
designs, manage complex data sets, and create accurate reports that contribute to 
meaningful research outcomes.

In addition to my informatics work, I am also pursuing my Master’s in Computer 
Science at the [University of Wisconsin - Whitewater](https://www.uww.edu/). 
My immediate goal is to apply advanced knowledge in Artificial Intelligence and 
Big Data to enhance my role as an Informatics Analyst.

Post-graduation, I aim to leverage these skills to drive tangible impacts in the 
field of informatics and pursue a PhD in Computer Science, with a focus on 
advancing big data analytics and AI, contributing to the continued evolution of 
the field.

<button onclick="window.scrollTo(0,0);">Go back to top</button>
